- name: install jenkins and docker on my remote servers
  hosts: Backend-Servers
  gather_facts: true
  roles:
    - role: docker
      tags: docker

    - role: jenkins
      tags: jenkins
    
    - role: maven
      tags: maven
