---
- name: Update repositories cache and install "ca-certificates" and "curl" packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - ca-certificates
    - curl


- name: Excuting some commands related to docker installation
  ansible.builtin.shell:
    cmd: |
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
  register: check_gpg_keys



- name: Update repositories cache again
  ansible.builtin.apt:
    update_cache: yes
  when: check_gpg_keys.changed == true


- name: Install docker packages
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  when: check_gpg_keys.changed == true
  register: check_docker



- name: Adding the ubuntu user to 'docker' group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes
  when: check_docker.changed == true