pipeline{
    
    agent any
    
    stages{
        
        stage('Build the app'){

          steps{
              
              script{
                    
                  def mvnHome = tool 'M3' // Name of the Maven installation in Jenkins
                  withMaven(maven: 'M3'){
                    // Name of the Maven installation in Jenkins
                    sh "'${mvnHome}/bin/mvn' clean package" // Build command
                  }
              }
          }
        }
        
        
        stage('Build th Docker Image'){

          steps{

            sh "docker build . -t mohanedahmed/petclinic-app:v${env.BUILD_NUMBER}"
            withCredentials([usernamePassword(credentialsId: 'myDockerHub', passwordVariable: 'pass', usernameVariable: 'user')]) {
                sh "docker login -u $user -p $pass"
            }
            sh "docker push mohanedahmed/petclinic-app:v${env.BUILD_NUMBER}"
          }            
        }
        
        stage('deploy'){

          steps{

            sh "docker-compose up -d"
          }     
        }
    }
}
